fix: push oci format image

diff --git a/.github/workflows/build_jenkins.yaml b/.github/workflows/build_jenkins.yaml
--- a/.github/workflows/build_jenkins.yaml
+++ b/.github/workflows/build_jenkins.yaml
@@ -32,10 +32,7 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
       - name: sync jnlp image
-        run: |
-          if ! docker pull ghcr.io/${{ github.repository_owner }}/inbound-agent:4.10-2; then
-            skopeo copy --multi-arch all docker://docker.io/jenkins/inbound-agent:4.10-2 docker://ghcr.io/${{ github.repository_owner }}/inbound-agent:4.10-2  
-          fi
+        run: skopeo copy -f oci --multi-arch all docker://docker.io/jenkins/inbound-agent:4.10-2 docker://ghcr.io/${{ github.repository_owner }}/inbound-agent:4.10-2
       - name: build jenkins
         uses: docker/build-push-action@v6
         with:
@@ -50,3 +47,10 @@ jobs:
             ghcr.io/${{ github.repository_owner }}/jenkins:latest
           cache-from: type=gha
           cache-to: type=gha,mode=max
+      - name: Convert Image to OCI Format
+        run: |
+          skopeo copy -f oci  --multi-arch all --retry-times 3 docker://ghcr.io/${{ github.repository_owner }}/jenkins:${{ inputs.container_tag }}-2.413 docker://ghcr.io/${{ github.repository_owner }}/jenkins:${{ inputs.container_tag }}-2.413
+          skopeo copy -f oci  --multi-arch all --retry-times 3 docker://ghcr.io/${{ github.repository_owner }}/jenkins:latest docker://ghcr.io/${{ github.repository_owner }}/jenkins:latest
+          
+          skopeo inspect docker://ghcr.io/${{ github.repository_owner }}/jenkins:${{ inputs.container_tag }}-2.413 | jq ".LayersData[0].MIMEType" | grep "oci" || {  echo "Error: ghcr.io/${{ github.repository_owner }}/jenkins:${{ inputs.container_tag }}-2.413 is not in oci format" ; exit 1 ;}
+          skopeo inspect docker://ghcr.io/${{ github.repository_owner }}/jenkins:latest | jq ".LayersData[0].MIMEType" | grep "oci" || { echo "Error: ghcr.io/${{ github.repository_owner }}/jenkins:latest is not in oci format" ; exit 1 ;}
